{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-helm-demo.serviceAccountName" . }}
  labels:
{{ include "eks-helm-demo.labels" . | nindent 4 }}
{{- end -}}
